#!/bin/bash

sudo mkdir -p /opt/boxen
sudo chown ${USER}:staff /opt/boxen
git clone https://github.com/acarl005/our-boxen /opt/boxen/repo
cd /opt/boxen/repo
alias apm="/opt/boxen/bin/apm"
./script/boxen --no-fde
